### ISSUE TITLE
is soundgether broken?

### ISSUE THREAD

**Issue by meriadec** [FortyTwo/soundgether#3]
Hi,

I was about to create a collaborative playlist for me and my friends, so I went to https://soundgether.keru.io/ but nothing happened. I checked my internet by pinging `google.com` and everything worked. I didn't understood what was happening right now, so I asked a friend to try at his home, and same problem again (ping google worked, and https://soundgether.keru.io/ didn't worked).

Is it a problem with internet itself, or maybe a problem with soundgether. Dunno, but I create the issue now for the moment, and I maybe will create an issue on the internet repo if the problem is not there.

Thanks for your help and your awesome work!

Collaboratively,
meriadec

**Comment by Kerumen** [comment]
I don't know how you find that link, but as in the repo description, the site url is http://soundgether.keru.io/. Maybe try with the correct link?

**Comment by balthazar** [comment]
Yeah I can reproduce too.

```
$> curl https://soundgether.keru.io 
curl: (7) Failed to connect to soundgether.keru.io port 443: Connection refused
```

Please fix.

**Comment by meriadec** [comment]
I was so disturbed, that I misstyped the repo name in the issue title.
My heart rate is getting back to normal now.

**Comment by Kerumen** [comment]
Haha nice try! You almost scared me!
Soundgether is still alive and fully working ;)

**Comment by meriadec** [comment]
nice `systemctl`skills, anyway :wink:

**Comment by Kerumen** [comment]
Nope, I didn't even restart the service. I did nothing.

**Comment by Apercu** [comment]
> I did nothing. — Kerumen

Can you swear it?

**Comment by meriadec** [comment]
![e1a8c3035cca38141d63e6c19fb747ff89e25418bceb8c42c32f8b26c9d0f790](https://cloud.githubusercontent.com/assets/315259/10863848/30ba42e2-7fd9-11e5-9f93-99fb7811bceb.jpg)

**Comment by Kerumen** [comment]
I promise. Don't trust me if you want but I **really** did nothing.
