### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by balthazar** [FortyTwo/soundgether#4]
Hi, I'm trying to register on the website but I can't. Can the soundgether team help me? Thanks.

**Comment by Kerumen** [comment]
Registering is not live yet (we are still in beta!)

However, PRs are welcome :)

**Comment by balthazar** [comment]
I'm afraid I don't know the architecture this project well enough to contribute in a significant way.. Are you expecting me to build your platform that will earn you advertising revenue once it replaces SoundCloud? 

Besides, closing an issue that way is not really inclusive of you and does not fit the vision I had of the sound**GETHER** project, which is pretty sad.

**Comment by meriadec** [comment]
Hey there ! I can confirm the register issue on my side (tried on three different devices, and even tried to re-format my Macbook / re-install Opera) : can't register either. Sounds like a problem with token, or something?

Beside that, @Apercu, yeah, I guess that a project called [whatever]**GETHER** is promoting inclusivity and will help you in any kind of manner. I'm sure of it.
